"""Add missing candidate columns

Revision ID: 2e38e8e1a8e3
Revises: 82be33a6c324
Create Date: 2026-03-10 21:17:25.067143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e38e8e1a8e3'
down_revision: Union[str, Sequence[str], None] = '82be33a6c324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_scores', sa.Column('overall_score', sa.Float(), nullable=True))
    op.drop_column('candidate_scores', 'total_score')
    op.add_column('candidates', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('candidates', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('candidates', 'last_name')
    op.drop_column('candidates', 'first_name')
    op.add_column('candidate_scores', sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('candidate_scores', 'overall_score')
    # ### end Alembic commands ###
