"""add_indexes

Revision ID: 82be33a6c324
Revises: 8b078809d47c
Create Date: 2026-03-09 16:22:23.826509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82be33a6c324'
down_revision: Union[str, Sequence[str], None] = '8b078809d47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interview_answers_session_id'), 'interview_answers', ['session_id'], unique=False)
    op.add_column('interview_sessions', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('interview_sessions', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.drop_column('interview_sessions', 'completed_at')
    op.drop_column('interview_sessions', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('started_at', sa.DATETIME(), nullable=True))
    op.add_column('interview_sessions', sa.Column('completed_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.drop_column('interview_sessions', 'end_time')
    op.drop_column('interview_sessions', 'start_time')
    op.drop_index(op.f('ix_interview_answers_session_id'), table_name='interview_answers')
    # ### end Alembic commands ###
