"""Add experience and duration fields

Revision ID: 9ff85cdbff07
Revises: ba5fe3f318ef
Create Date: 2026-03-11 13:56:34.884502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff85cdbff07'
down_revision: Union[str, Sequence[str], None] = 'ba5fe3f318ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('source', sa.String(), nullable=True))
    op.add_column('interview_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'duration_minutes')
    op.drop_column('candidates', 'source')
    op.drop_column('candidates', 'years_of_experience')
    # ### end Alembic commands ###
